<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName Condition="'$(ProductEdition)' == 'Standard'">PixelCompanion.Updater</AssemblyName>
    <AssemblyName Condition="'$(ProductEdition)' == 'Yaroro'">PixelCompanion.Yaroro.Updater</AssemblyName>
    <RootNamespace>PixelCompanion.Updater</RootNamespace>
    <ApplicationIcon Condition="'$(ProductEdition)' == 'Yaroro'">..\..\assets\icons\yaroro-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PixelCompanion.Core\PixelCompanion.Core.csproj" />
  </ItemGroup>
</Project>
